import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { Hero } from "@/components/hero";
import { Panel } from "@/components/panel";
import { useResultsExport, useXmpExport } from "@/features/export/use-export";
import { useJobId } from "@/hooks/use-job-id";
export function ExportRoute() {
    const jobId = useJobId();
    const [format, setFormat] = useState("csv");
    const xmpExport = useXmpExport();
    const resultsExport = useResultsExport();
    return (_jsxs(_Fragment, { children: [_jsx(Hero, { title: "Dry-run first, then commit metadata writes.", copy: "ARW \u306F\u30B5\u30A4\u30C9\u30AB\u30FC\u524D\u63D0\u3001JPEG \u306F\u8A55\u4FA1\u30BF\u30B0\u306E\u307F\u4FDD\u5B88\u7684\u66F4\u65B0\u3067\u3059\u3002ExifTool \u672A\u5C0E\u5165\u6642\u306F\u3053\u3053\u3060\u3051\u6B62\u3081\u307E\u3059\u3002", badge: "Export" }), _jsxs("div", { className: "grid cols-2", children: [_jsxs(Panel, { title: "XMP Write-back", copy: "`dry_run=true` \u304C\u65E2\u5B9A\u3067\u3059\u3002", children: [_jsxs("div", { className: "actions", children: [_jsx("button", { className: "button secondary", type: "button", onClick: () => xmpExport.mutate({ jobId, dryRun: true }), children: "Run Dry-Run" }), _jsx("button", { className: "button warning", type: "button", onClick: () => xmpExport.mutate({ jobId, dryRun: false }), children: "Commit XMP" })] }), xmpExport.data ? (_jsxs("div", { className: "grid", style: { marginTop: 20 }, children: [_jsxs("div", { className: "score-row", children: [_jsxs("span", { className: "score-chip", children: ["Target ", xmpExport.data.target_count] }), _jsxs("span", { className: "score-chip", children: ["Writable ", xmpExport.data.writable_count ?? xmpExport.data.written_count ?? 0] }), _jsxs("span", { className: "score-chip", children: ["Blocked ", xmpExport.data.blocked_count ?? xmpExport.data.failed_count ?? 0] })] }), xmpExport.data.write_candidates?.map((item) => (_jsxs("div", { className: "list-card", children: [_jsx("strong", { children: item.photo_id }), _jsx("p", { className: "panel-copy", children: item.summary })] }, item.photo_id))), xmpExport.data.conflicts?.map((item, index) => (_jsxs("div", { className: "list-card", children: [_jsx("strong", { children: item.result_code ?? "conflict" }), _jsx("p", { className: "panel-copy", children: item.summary })] }, `${item.result_code}-${index}`)))] })) : null] }), _jsxs(Panel, { title: "Result Export", copy: "\u30EC\u30D3\u30E5\u30FC\u7D50\u679C\u3092 CSV / JSON \u3067\u6301\u3061\u51FA\u3057\u307E\u3059\u3002", children: [_jsx("div", { className: "field-grid", children: _jsxs("div", { className: "field", children: [_jsx("label", { htmlFor: "format", children: "Format" }), _jsxs("select", { id: "format", value: format, onChange: (event) => setFormat(event.target.value), children: [_jsx("option", { value: "csv", children: "CSV" }), _jsx("option", { value: "json", children: "JSON" })] })] }) }), _jsx("div", { className: "actions", style: { marginTop: 20 }, children: _jsx("button", { className: "button", type: "button", onClick: () => resultsExport.mutate({ jobId, format }), children: "Export Results" }) }), resultsExport.data ? _jsx("p", { className: "panel-copy", children: resultsExport.data.export_path }) : null] })] })] }));
}
